# Convolutional Neural Network

### Remember and Check Notes:
>As long as we haven't reached the final output layer, we should use the 'relu' activation function.

> For Binary classification: `Sigmoid` activation function,

> For Multi-class classification: `Softmax` activation function.

### Importing the libraries

In [8]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import image_dataset_from_directory

In [9]:
#Preprocessing the training set
train_datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2, 
    horizontal_flip=True
)
training_dataset= train_datagen.flow_from_directory(
                '/kaggle/input/cnn-cats-and-dogs/Section 40 - Convolutional Neural Networks (CNN)/dataset/training_set',
                target_size=(64,64),
                batch_size=32,
                class_mode='binary')

Found 8000 images belonging to 2 classes.


In [10]:
#Preprocessing the test set
test_datagen=ImageDataGenerator(rescale=1./255)
test_dataset= test_datagen.flow_from_directory(
            '/kaggle/input/cnn-cats-and-dogs/Section 40 - Convolutional Neural Networks (CNN)/dataset/test_set',
            target_size=(64,64),
            batch_size=32,
            class_mode='binary')

Found 2000 images belonging to 2 classes.


## Part 2 - Building the CNN

### Initialising the CNN

In [12]:
cnn=tf.keras.models.Sequential()

### Step 1 - Convolution

In [14]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation= 'relu', input_shape=(64,64,3)))
#filters= randomly choosen no. of filters
#kernel_size = dimensions of filter(3=3x3)
#input_shape=(64->given above, 3-> RGB color, 1-> Black&White colour)

### Step 2 - Pooling

In [15]:
cnn.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2),
    strides=2,
    data_format=None,
    name=None,
))
# pool_size= When we create pooled feature map from the feature map, dimensions of the square,
#which gives us features from the feature map, is the pool_size.
#strides= steps-taken by the pool_matrix in the feature_matrix while forming the pooled feature_matrix.

### Adding a second convolutional layer

In [16]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation= 'relu'))
cnn.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2),
    strides=2,
    data_format=None,
    name=None,
))
#Input_shape was defined just for the first layer to connect the input_layer to the first convolutional network

### Step 3 - Flattening

In [19]:
cnn.add(tf.keras.layers.Flatten(
    data_format=None
))

### Step 4 - Full Connection

In [21]:
#Implementing a fully connected ANN from hereon:
cnn.add(tf.keras.layers.Dense(units=128,
                             activation='relu',
                             ))
#units= No. of neurons, usually higher the number, better the accuracy, hence we are using 128.

### Step 5 - Output Layer

In [22]:
cnn.add(tf.keras.layers.Dense(units=1,
                             activation='sigmoid'
                             ))
# We are using binary classification, hence 1 neuron for either 'cat' or 'dog'.


## Part 3 - Training the CNN

### Compiling the CNN

In [24]:
cnn.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

### Training the CNN on the Training set and evaluating it on the Test set

In [25]:
cnn.fit(x=training_dataset,validation_data=test_dataset,epochs=25)

Epoch 1/25


/opt/conda/lib/python3.10/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


250/250 ━━━━━━━━━━━━━━━━━━━━ 103s 395ms/step - accuracy: 0.5239 - loss: 0.6929 - val_accuracy: 0.6115 - val_loss: 0.6536
Epoch 2/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 101s 236ms/step - accuracy: 0.6337 - loss: 0.6370 - val_accuracy: 0.7040 - val_loss: 0.5801
Epoch 3/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 83s 241ms/step - accuracy: 0.6983 - loss: 0.5643 - val_accuracy: 0.7275 - val_loss: 0.5451
Epoch 4/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 61s 241ms/step - accuracy: 0.7528 - loss: 0.5066 - val_accuracy: 0.7295 - val_loss: 0.5382
Epoch 5/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 60s 238ms/step - accuracy: 0.7809 - loss: 0.4639 - val_accuracy: 0.7800 - val_loss: 0.4948
Epoch 6/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 82s 237ms/step - accuracy: 0.8007 - loss: 0.4211 - val_accuracy: 0.7860 - val_loss: 0.4645
Epoch 7/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 83s 240ms/step - accuracy: 0.8273 - loss: 0.3891 - val_accuracy: 0.7865 - val_loss: 0.4605
Epoch 8/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 82s 238ms/step - accuracy: 0.8475 - loss: 0.3573 - v

## Part 4 - Making a single prediction

### Predict method expects a 2-D array. remember we used [[]] earlier.
> Hence, we have to convert the image to a 2-D array (PIL image instance into a numpy array).

>Also we trained our cnn model on batches, hence we have to predict this 'single image' in a batch
as well, although the batch will just contain this single image only. The CNN model recognizes this
batch as an extra dimension.

>The batch is always the first dimension or axis=0


In [44]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('/kaggle/input/cnn-cats-and-dogs/Section 40 - Convolutional Neural Networks (CNN)/dataset/single_prediction/cat_or_dog_1.jpg',
                           target_size=(64,64))
test_image=image.img_to_array(test_image) #3-D (dim.,dim.,RGB)
test_image=np.expand_dims(test_image, axis=0) #4-D (batch,dim.,dim.,RGB)
result= cnn.predict(test_image/255.0)
# We normalized the result above, to get the value of test image (RGB values) between 0-1, to
#make it easier for the neural network model to predict on

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


### Explanation for normalizing above by doing: cnn.predict(test_image/255.0)
Some activation functions, like the sigmoid or tanh functions, saturate when the input values are too large or too small. Normalizing the input data helps in preventing saturation of these activation functions, allowing them to operate in their more linear and effective range.

In [45]:
test_image

array([[[[ 54.,  58.,   7.],
         [ 58.,  63.,   9.],
         [ 64.,  67.,  10.],
         ...,
         [136., 144.,  71.],
         [140., 150.,  77.],
         [139., 149.,  78.]],

        [[ 48.,  54.,   6.],
         [ 51.,  58.,   7.],
         [ 58.,  63.,   9.],
         ...,
         [129., 137.,  64.],
         [139., 149.,  78.],
         [141., 151.,  80.]],

        [[ 48.,  56.,   7.],
         [ 48.,  56.,   7.],
         [ 54.,  61.,  10.],
         ...,
         [123., 129.,  65.],
         [136., 145.,  80.],
         [140., 149.,  82.]],

        ...,

        [[ 46.,  55.,  12.],
         [ 42.,  50.,  11.],
         [ 38.,  49.,   9.],
         ...,
         [239., 205., 170.],
         [235., 209., 186.],
         [231., 201., 173.]],

        [[ 50.,  57.,  13.],
         [ 42.,  50.,  11.],
         [ 44.,  52.,  11.],
         ...,
         [234., 200., 163.],
         [236., 206., 178.],
         [234., 203., 175.]],

        [[ 53.,  59.,  13.],
       

In [46]:
result

array([[1.]], dtype=float32)

In [47]:
training_dataset.class_indices

{'cats': 0, 'dogs': 1}

#### Result is a 2-D array of dimensions: 1x1. (batch no. x size). hence we use [][] to access the first element.

In [48]:
if result[0][0]==0:
    prediction= 'cat'
else:
    prediction= 'dog'

In [49]:
print(prediction)

dog


#### Predicting for the entire test dataset:

In [50]:
ans=cnn.predict(test_dataset)

63/63 ━━━━━━━━━━━━━━━━━━━━ 8s 118ms/step


In [51]:
ans

array([[8.2308743e-06],
       [1.4541250e-04],
       [1.6004703e-10],
       ...,
       [1.6358247e-12],
       [9.2058319e-15],
       [9.8086727e-01]], dtype=float32)

In [55]:
threshold =0.5
predicted_labels = np.where(ans >= threshold, "dog", "cat")

In [56]:
predicted_labels

array([['cat'],
       ['cat'],
       ['cat'],
       ...,
       ['cat'],
       ['cat'],
       ['dog']], dtype='<U3')